Aliucord/Aliucord

- Aliucord/build.gradle
- Aliucord/src/main/AndroidManifest.xml
- Aliucord/src/main/java/com/aliucord/Utils.java
- Aliucord/src/main/java/com/aliucord/api/CommandsAPI.java
- Aliucord/src/main/java/com/aliucord/entities/MessageEmbed.java
- Aliucord/src/main/java/com/aliucord/entities/MessageEmbedBuilder.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- installer/android/app/build.gradle
- installer/android/build.gradle
Plugin developers can now customize Clyde's name and avatar, making it more user friendly and unique per plugin.
`CommandsAPI.CommandResult` got 2 new parameters in the constructor, those are `username` and `avatarUrl`. `username` is used for the bot name and `avatarUrl` is the URL used for bot's avatar. Note: URL set in `avatarUrl` must point to raw image and not a redirect.
```java
MessageEmbed embed = new MessageEmbedBuilder()
.setTitle("Drac")
.setDescription("Haha Jonathan, you are banging my daughter.")
.build();
return new CommandsAPI.CommandResult(null, embed, "Drac", "https://i.kym-cdn.com/entries/icons/original/000/037/312/cover2.jpg", false)
```
MessageEmbed has been renamed to MessageEmbedBuilder and the `embed` field is now private, instead plugin developers should use the …
> Clyde Customizations and other improvements

- Aliucord/src/main/java/com/aliucord/utils/RxUtils.java
Example usage:
```java
var api = RestAPI.getApi();
var obs = api.getChannelMessagesAround(811261478875299840L, 5, 854461004657721365L);
var result = RxUtils.getResultBlocking(obs);
if (result.second != null) {
Log.e("Oh no", "Horrible Error", result.second);
return null;
} else {
return new CommandsAPI.CommandResult("Wow it worked!!", null, false);
}
```
> Add RxUtils.getResultBlocking

- Aliucord/src/main/java/com/aliucord/fragments/ConfirmDialog.java
- Aliucord/src/main/java/com/aliucord/fragments/InputDialog.java
- DiscordStubs/src/main/java/com/discord/databinding/WidgetKickUserBinding.java
- DiscordStubs/src/main/java/com/discord/views/RadioManager.java
- DiscordStubs/src/main/java/com/discord/widgets/guilds/leave/WidgetLeaveGuildDialog$binding$2.java
- DiscordStubs/src/main/java/com/discord/widgets/user/WidgetKickUser$binding$2.java
- DiscordStubs/src/main/java/com/lytefast/flexinput/R$c.java
Example usage:
```java
var dialog = new InputDialog()
.setPlaceholderText("Filename")
.setTitle("Filename")
.setDescription("Please specify a name for this theme");
dialog.setOnOkListener(e -> {
var text = dialog.getInput();
if (text.length() > 0) {
try {
importTheme(contentUri, text);
} catch (Throwable ex) {
Themer.logger.error(requireContext(), "Failed to import theme.", ex);
}
dialog.dismiss();
}
});
dialog.show(getParentFragmentManager(), "Themer");
```
Result:
> add InputDialog fragment & improve ConfirmDialog

- Aliucord/src/main/java/com/aliucord/api/CommandsAPI.java
Currently when a error is made by a plugin it will show the author but if a plugin has multiple authors it will only show the first author and not the other authors
> Errors Not Showing Multiple Authors

- Aliucord/src/main/java/com/aliucord/Http.java
- Aliucord/src/main/java/com/aliucord/Main.java
Utils.appActivity is recreated on actions like device rotating, which makes it so that you can't use its supportFragmentManager anymore for doing stuff like showing dialogs. This adds a patch to keep it up to date. Additionally some minor Http tweaks
> Small fixes

- Aliucord/src/main/java/com/aliucord/Main.java
- Aliucord/src/main/java/com/aliucord/PluginManager.java
- Aliucord/src/main/java/com/aliucord/coreplugins/CorePlugins.java
This change sorts plugins & coreplugins before loading & starting them. It allows easier finding of log messages, as well as reproducibility on plugin conflicts.
> feat: sort plugins before loading/starting

- Aliucord/src/main/java/com/aliucord/Http.java
Automatically adds headers and allows you to remove the `https://discord.com/api/v9` base url
> Add DiscordRequest to Http

- Aliucord/src/main/java/com/aliucord/SettingsUtils.java
- Aliucord/src/main/java/com/aliucord/SettingsUtilsJSON.kt
Until we migrate ac's internal settings to use json this will have to do
I thought Manti would add these from my earlier pr (#117) but apparently not.
> feat(SettingsUtils): missing operations

- Injector/src/main/java/com/aliucord/injector/Injector.java
Very cursed code, but it works
Any further reflection calls on hidden methods will succeed during the apps lifetime
> feat(Injector): disable hidden api policy

- README.md
*hopefully will prevent people asking if aliucord does it/asking for no track plugins*
but lets be honest people wont read this either
> [skip ci] Add "Blocked Discord Tracking/Analytics" to README features

- Aliucord/src/main/java/com/aliucord/fragments/AppFragmentProxy.java
- Aliucord/src/main/java/com/aliucord/fragments/FragmentProxy.java
Very hacky fix. On rotate, simply simulate backpress (Close page) and
return new Fragment. Fixes crash, but kicks you out of the settings page
on rotate.
> Fix rotate crash in settings

- Aliucord/src/main/java/com/aliucord/coreplugins/UploadSize.kt
https://stackoverflow.com/a/18204596
> To upload data to a web server, configure the connection for output using setDoOutput(true).
For best performance, you should call either setFixedLengthStreamingMode(int) when the body length is known in advance, or setChunkedStreamingMode(int) when it is not. Otherwise HttpURLConnection will be forced to buffer the complete request body in memory before it is transmitted, wasting (and possibly exhausting) heap and increasing latency.
(I of course tested it)
andro will explode
> hopefully fix upload progress jumping right into 99%

- Aliucord/src/main/java/com/aliucord/api/GatewayAPI.kt
Provides any easy way to receive gateway events.
Ex. (Kotlin)
```kt
data class ChannelPinsUpdatePayload(
val guildId: Long?,
val channelId: Long,
val lastPinTimestamp: String?
)
GatewayAPI.onEvent<ChannelPinsUpdatePayload>("CHANNEL_PINS_UPDATE") { payload ->
logger.debug("Pins updated in ${payload.channelId}")
}
```
Ex. (Java)
```java
GatewayAPI.onEvent("CHANNEL_PINS_UPDATE", ChannelPinsUpdatePayload.class, (payload) -> {
logger.debug("Pins updated in " + payload.channelId);
});
```
> Feat: Gateway API

- Aliucord/src/main/java/com/aliucord/coreplugins/CorePlugins.kt
- Aliucord/src/main/java/com/aliucord/coreplugins/EnablePrivateThreads.kt
It is very simple and overrides the checking for nitro when trying to create a private Thread, and also hides the text that says "level 2" or "unlocked"
> Add PrivateThreads coreplugin

- Aliucord/src/main/java/com/aliucord/coreplugins/rn/Patches.kt
- Aliucord/src/main/java/com/aliucord/coreplugins/rn/RNAPI.kt
Added a patch that makes default avatar use the user id if their discriminator is gone
> fix: use id if discrim gone

- Aliucord/src/main/java/com/aliucord/coreplugins/rn/Patches.kt
- Aliucord/src/main/java/com/aliucord/coreplugins/rn/RNAPI.kt
Removed the validation for discriminator, and also hide's the discriminator input entirely if the user has already been moved to the new username system.
> fix: remove discrim validation for updating username

- Aliucord/src/main/java/com/aliucord/Main.java
I was inspired by e63cc053bcfa1cf012375587a13f9481bb185f6a to check out some other experiments and found an experiment that allows me to edit my server pfp/banner/bio, so it would be nice to have it enabled by default. I don't have building setup, but this should work.
> Enable experiment for editing server profile, banner, and bio by default

- Aliucord/src/main/java/com/aliucord/api/GatewayAPI.kt
- Aliucord/src/main/java/com/aliucord/utils/GsonUtils.kt
Uses GSON instead of JSONObject for event deserialization for the name, gson appears to use streams under the hood so that should be better.
Also touched up the documentation :)
> fix(GatewayAPI): parse incoming events more efficiently

- Aliucord/src/main/java/com/aliucord/updater/ManagerBuild.kt
- Aliucord/src/main/java/com/aliucord/utils/GsonUtils.kt
- Aliucord/src/main/java/com/aliucord/utils/SemVer.kt
Manager injects a config file into the APK with the versions of builds that were used to patch & install the APK. This parses and exposes that data.
> feat: installation components versions API

- Aliucord/src/main/java/com/aliucord/Main.java
- Aliucord/src/main/java/com/aliucord/PluginManager.java
- Aliucord/src/main/java/com/aliucord/coreplugins/ExperimentDefaults.kt
Add more experiment defaults after Discord stopped deleted them for v126.21
> feat: set experiment defaults

- Aliucord/src/main/java/com/aliucord/PluginManager.java
- Aliucord/src/main/java/com/aliucord/coreplugins/StickerCrashFix.kt
Discord stickers (including the cursed pineapple pizza sticker) may not set APNG delay properly. The official spec specifies some defaults, and in addition to some legacy web issues, the de-facto minimum delay is 100ms, as also seen on desktop Discord.
Without this, a division-by-zero occurs, and the app crashes when rendering such stickers.
ref: https://github.com/davidmz/apng-js/blob/52f6fab62ffabe2abac3467d6abf82fe98ba4018/src/library/parser.js#L62-L73
> fix: crash due to bad apng stickers

- Aliucord/src/main/java/com/aliucord/coreplugins/StickerCrashFix.kt
Only set delay to 100 if it is lesser than or equal to 10, which is apparently what most web browsers do.
> fix(StickerCrashFix): fix some stickers being slowed down

- Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginFile.kt
#520 introduced a regression where plugins in most cases will not start upon installation. This is because `PluginManager.enablePlugin` skips plugin starting if the plugin is already enabled (which it usually is).
This PR fixes it by ensuring that new, enabled plugins are always started.
> fix(PluginDownloader): ensure new plugins are started

- Aliucord/src/main/java/com/aliucord/coreplugins/GifPreviewFix.kt
Previously the core plugin removed the scaled size parameters. This PR keeps them to make sure gifs are scaled properly, and prevents a crash when loading large gifs.
Closes #563
> fix(GifPreviewFix): fix possible crash on large gifs

- patches/src/b/i/c/m/d/o/h.patch
- patches/src/b/i/c/m/e/b.patch
i made smali patches which stops  `.com.google.firebase.crashlytics` and `.com.google.firebase.crashlytics-ndk` from being made so they don't add an additional 16kB on startup which overtime can increase the user data size by alot
> feat: stop crashlytics folder from being made on startup

- Aliucord/src/main/java/com/aliucord/PluginManager.kt
- Aliucord/src/main/java/com/aliucord/coreplugins/AlignThreads.kt
i changed the threads icon from 20dp to 24dp in the chat actions menu/channel actions so it doesn't look off between the rest of the icons which are 24dp
> feat(CorePlugins): add AlignThreads fix

- Aliucord/src/main/java/com/aliucord/coreplugins/rn/Patches.kt
Smali patching in GIF formatType breaks things that work fine with current `Patches.kt`, and the only feature that's actually missing is the ability to send links to gif stickers, so I patched the fallback `""` format extension to be `".gif"` instead since there is no more sticker types anyway.
> feat(Patches): add `.gif` sticker format

- Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginDownloader.kt
PluginDownloader always downloads from `builds`  even if different ref is specified in the link
> fix(PluginDownloader): use original ref from links

- Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginDownloader.kt
for some reason the code checks twice if a message has a plugin zip file so as a result, there would be 2 buttons which are "Install {plugin}" and "Install {plugin}.zip"..
> fix(PluginDownloader): duplicate install buttons in plugin development channel

- Aliucord/src/main/java/com/aliucord/settings/AliucordPage.kt
- Injector/src/main/java/com/aliucord/injector/Injector.kt
No longer copy the local/custom core bundle to the same place as the official core bundle. This makes switching much easier for users who are smart enough to enable it but then too dumb to know how to clear the cache afterwards.
> fix: separate original and custom core bundles

- Aliucord/src/main/java/com/aliucord/coreplugins/RemoveBilling.kt
for some reason, when tapping on the billing settings header it redirects to the nitro page which is what removebilling was meant to remove, it also makes a bit more clutter in the settings ui, this will also bring the nitro gifting button to user settings
> feat: remove billing settings/nitro header
