Aliucord/src/main/java/com/aliucord/entities/MessageEmbed.java
additionally returns self in all setters so you can chain
I didn't test this because the installer gets stuck on Installing indefinitely when enabling use dex from storage so no clue whether it works correctly lmao
I think it'd be good if there was a `change git upstream` option in installer so you can use your fork in it and didnt have to use dex from storage. I'll try to add it but i have no idea how flutter works so idk if i'll figure it out lmao
=> add classes for Author, Footer, Provider and Image and add useful methods

Aliucord/src/main/java/com/aliucord/Http.java, Aliucord/src/main/java/com/aliucord/HttpUtils.java, Aliucord/src/main/java/com/aliucord/updater/PluginUpdater.java
Adds RequestBuilder kinda similar to the Powercord one to ease sending HttpRequests. Does not have querystring support yet and I also haven't tested it yet so its still a draft
=> Add HttpUtils Request/Response classes to ease making Http Requests

Aliucord/src/main/java/com/aliucord/settings/Plugins.java, Aliucord/src/main/java/com/aliucord/widgets/PluginCard.java
Makes it so that the plugins page shows plugins in alphabetical order
=> Sort plugins alphabetically

Aliucord/src/main/java/com/aliucord/views/Button.java, Aliucord/src/main/java/com/aliucord/views/DangerButton.java, DiscordStubs/src/main/java/com/lytefast/flexinput/R$h.java
Implements proper buttons, which use Discord's styles.
Old APIs were deprecated
=> Implement proper Button APIs

Aliucord/src/main/java/com/aliucord/api/CommandsAPI.java, Aliucord/src/main/java/com/aliucord/api/NotificationsAPI.java, Aliucord/src/main/java/com/aliucord/api/PatcherAPI.java, Aliucord/src/main/java/com/aliucord/api/SettingsAPI.java, Aliucord/src/main/java/com/aliucord/views/Button.java, Aliucord/src/main/java/com/aliucord/views/DangerButton.java
Added some basic documentation, not fully complete but at least it gives some hints about what APIs do.
=> add basic JavaDoc

Aliucord/src/main/java/com/aliucord/Utils.java, Aliucord/src/main/java/com/aliucord/settings/Plugins.java, Aliucord/src/main/java/com/aliucord/settings/Updater.java, Aliucord/src/main/java/com/aliucord/views/TextInput.java, Aliucord/src/main/java/com/aliucord/widgets/PluginCard.java, Aliucord/src/main/java/com/aliucord/widgets/UpdaterPluginCard.java
- Fixed cards for AMOLED
- Set card corner radius to 8dp
- Migrated to new Button and DangerButton
- Use RecyclerView item divider
#7 can be closed because this PR does the same thing.
=> Adjusted Settings layout

Aliucord/src/main/java/com/aliucord/api/CommandsAPI.java
Wraps the command execution block into a try catch(Throwable) and presents the user a nice error message with debug info to show to the plugin dev
Additionally this allows returning null or CommandResult(null) from commands
=> Catch and gracefully handle command errors

Aliucord/src/main/java/com/aliucord/api/NotificationsAPI.java, Aliucord/src/main/java/com/aliucord/entities/NotificationData.java, Aliucord/src/main/java/com/aliucord/updater/PluginUpdater.java
Replaced direct field calls with getters and setters as they're more convenient, also added documentation. Some of docs are most likely invalid so I added a `FIXME` annotation to them.
- This **will** break the current implementation
=> Improved notification API

Aliucord/src/main/java/com/aliucord/api/CommandsAPI.java, Aliucord/src/main/java/com/aliucord/utils/RxUtils.java, Aliucord/src/main/java/com/aliucord/wrappers/ChannelWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/GuildEmojiWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/GuildMemberWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/GuildWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/PermissionOverwriteWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/AuthorWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/FieldWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/FooterWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/ImageWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/MessageEmbedWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/ProviderWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/ThumbnailWrapper.java, Aliucord/src/main/java/com/aliucord/wrappers/embeds/VideoWrapper.java, DiscordStubs/src/main/java/com/discord/api/permission/Permission.java, DiscordStubs/src/main/java/com/discord/api/permission/PermissionOverwrite.java, DiscordStubs/src/main/java/com/discord/stores/StorePermissions.java, DiscordStubs/src/main/java/com/discord/stores/StoreStream.java, DiscordStubs/src/main/java/com/discord/utilities/icon/IconUtils.java, DiscordStubs/src/main/java/com/discord/utilities/permissions/PermissionUtils.java, DiscordStubs/src/main/java/com/discord/utilities/rest/RestAPI.java
- Adds Permission related Stubs & Wrapper (All permission BITS, PermissionUtils, StorePermissions)
- Refactors all wrappers to use static method (and instance methods calling them for convenience), so that you dont have to create a new class everytime. this should drastically increase performance when doing stuff like 
```java
CollectionUtils.filter(biiiigList, e -> new SomeWrapper(e).someMethod())
``` 
which could now be changed to
```java
CollectionUtils.filter(biiiigList, e -> SomeWrapper.someMethod(e))
```
=> Wrapper/Stubs Refactor & Minor fixes

Aliucord/src/main/java/com/aliucord/views/SaveButton.java, DiscordStubs/src/main/java/com/lytefast/flexinput/R$d.java
You can use `(FloatingActionButton) saveButtonLayout.getChildAt(0)` to get the `FloatingActionButton`. Useful functions will be `saveButton.hide()`, `saveButton.show()`, and `saveButton.setOnClickListener((View view) -> {})`.
=> Add SaveButton view

Aliucord/src/main/java/com/aliucord/Main.java, Aliucord/src/main/java/com/aliucord/Utils.java, Aliucord/src/main/java/com/aliucord/settings/Crashes.java, Aliucord/src/main/java/com/aliucord/settings/Plugins.java, DiscordStubs/src/main/java/com/lytefast/flexinput/R$d.java
=> add crash handler & logger

Aliucord/src/main/java/com/aliucord/Constants.java, Aliucord/src/main/java/com/aliucord/fragments/SettingsPage.java, Aliucord/src/main/java/com/aliucord/settings/Crashes.java, Aliucord/src/main/java/com/aliucord/settings/Plugins.java, DiscordStubs/src/main/java/com/lytefast/flexinput/R$d.java
This also fixes the padding for the crashes page, as it was using half the regular padding for some unknown reason
=> Add toolbar buttons to both the Plugins and Crashes settings pages

Aliucord/src/main/java/com/aliucord/Main.java, Aliucord/src/main/java/com/aliucord/PluginManager.java, Aliucord/src/main/java/com/aliucord/coreplugins/CommandHandler.java, Aliucord/src/main/java/com/aliucord/coreplugins/CoreCommands.java, Aliucord/src/main/java/com/aliucord/coreplugins/CorePlugins.java, Aliucord/src/main/java/com/aliucord/coreplugins/NoTrack.java, Aliucord/src/main/java/com/aliucord/coreplugins/TokenLogin.java
This prevents them from showing up in Javadoc
=> make coreplugins package-private

DiscordStubs/src/main/java/com/discord/stores/StoreUserSettings.java
Updated the StoreUserSettings stub for latest Discord version
=> Update StoreUserSettings stub

Aliucord/src/main/java/com/aliucord/Http.java, Aliucord/src/main/java/com/aliucord/Main.java, Aliucord/src/main/java/com/aliucord/Utils.java, Aliucord/src/main/java/com/aliucord/api/CommandsAPI.java, Aliucord/src/main/java/com/aliucord/api/PatcherAPI.java, Aliucord/src/main/java/com/aliucord/entities/MessageEmbedBuilder.java, Aliucord/src/main/java/com/aliucord/settings/Plugins.java, Aliucord/src/main/java/com/aliucord/utils/ReflectUtils.java, Aliucord/src/main/java/com/aliucord/utils/RxUtils.java
Several API improvements:
- Request:
- Implement Closeable
- Set Content-Length header when sending post data
- Add method for sending x-www-form-urlencoded data
- RxUtils: Use CountdownLatch instead of lock
- ReflectUtils:
- Deprecate `boolean priv` parameter everywhere. Setting accessible to true is more performant even if the field is public and it saves you one argument
- Add findMethodByArgs and invokeMethodWithArgs
- Utils:
- Cache getResId result
- add pipe and launchUrl
=> API improvements

Aliucord/src/main/java/com/aliucord/settings/Updater.java, Aliucord/src/main/java/com/aliucord/updater/PluginUpdater.java, Aliucord/src/main/java/com/aliucord/updater/Updater.java
=> Updater: add Aliucord update notifications

Injector/src/main/java/com/aliucord/injector/Injector.java
Should probably be tested by others first to make sure it works
=> Injector: Use better method for adding dex to classpath

Aliucord/src/main/java/com/aliucord/Main.java
May or may not work I did this on mobile
=> Add debuggable to app info

Aliucord/src/main/java/com/aliucord/Http.java, Aliucord/src/main/java/com/aliucord/updater/PluginUpdater.java, Aliucord/src/main/java/com/aliucord/utils/IOUtils.java
- make saveToFile save to temp file and then move to the actual path. This ensures files aren't overwritten with garbage/nothing if something goes wrong
- Add option to verify integrity using md5sum 
The gradle plugin would then calculate and add m5sums to the updater.json
Draft because I still need to add it to the gradle plugin and also test that it works correctly
=> Add sha1 Integrity check to Http#saveToFile & Plugin Updater

Aliucord/src/main/java/com/aliucord/entities/CommandContext.java
Add missing command option getters
=> feat(CommandContext): role/channel option getters

Aliucord/src/main/java/com/aliucord/Main.java, Aliucord/src/main/java/com/aliucord/Utils.kt
This was nearly added by #52 but closed due to obsolescence.
=> feat: store instance of WidgetChatList

Aliucord/src/main/java/com/aliucord/SettingsUtilsJSON.kt
all plugin configs that is using set/getObject should be deleted,otherwise it may cause errors
=> edited jsonsettings

Aliucord/src/main/java/com/aliucord/SettingsUtilsJSON.kt
I tested it on my device a few times,if it still throws erros skill issue
=> hopefully fixed jsonsettings

Aliucord/src/main/java/com/aliucord/coreplugins/CoreCommands.kt
=> feat(CoreCommands): separate /plugins into enabled/disabled

Aliucord/src/main/java/com/aliucord/SettingsUtilsJSON.kt, Aliucord/src/main/java/com/aliucord/api/SettingsAPI.java, Aliucord/src/main/java/com/aliucord/settings/SettingsDelegates.kt
Usage:
```kt
var settingName: SettingType by settings.delegate(defaultValue)
```
=> Add delegation for settings

Aliucord/src/main/java/com/aliucord/Utils.kt
Move snackbar above system navigation bar
=> Fix snackbar positioning

Aliucord/src/main/java/com/aliucord/PluginManager.java, Aliucord/src/main/java/com/aliucord/coreplugins/CommandHandler.kt, Aliucord/src/main/java/com/aliucord/coreplugins/CoreCommands.kt, Aliucord/src/main/java/com/aliucord/coreplugins/NoTrack.java, Aliucord/src/main/java/com/aliucord/coreplugins/SupportWarn.kt, Aliucord/src/main/java/com/aliucord/coreplugins/TokenLogin.java, Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginDownloader.kt, Aliucord/src/main/java/com/aliucord/entities/Plugin.java, Aliucord/src/main/java/com/aliucord/utils/GsonUtils.java
Closes #174
Might be supplemented by `PluginManger` and `Plugin` kotlin rewrites later, but that will probably be breaking change
=> Simplify plugin loading process

Aliucord/src/main/java/com/aliucord/coreplugins/CoreCommands.kt
=> fix: add plugin count to /plugins

Aliucord/src/main/java/com/aliucord/Utils.kt
hatred
itll show at the top now instead but guaranteed to work 💯
=> fix Utils.promptRestart

Aliucord/src/main/java/com/aliucord/Constants.java, Aliucord/src/main/java/com/aliucord/coreplugins/SupportWarn.kt, Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginDownloader.kt, Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginFile.kt
Like what themer does, but for plugins
Useful for sending people plugins to test
heres a sample: https://discord.com/channels/811255666990907402/811261478875299840/908566566310907905
=> feat: install plugin zips from dev channel

.github/workflows/build-installer.yml, README.md, installer/android/app/src/main/AndroidManifest.xml, installer/lib/github.dart, installer/lib/pages/home.dart, installer/lib/pages/install.dart, installer/lib/widgets/commits.dart, installer/lib/widgets/init_install.dart, installer/lib/widgets/update_dialog.dart
Should also fix annoying issue with having rebuild Injector to make installer detect new base update.
(workflow is not tested btw :trollface:)
=> move installer builds to releases

Aliucord/src/main/java/com/aliucord/coreplugins/SupportWarn.kt
* Stopped patching if the user has already agreed to both
=> Cleaned up SupportWarn

Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginDownloader.kt
Somebody pointed it out, here fix
=> fix(PluginDownloader): multiple plugin zips per message in dev channel

Aliucord/src/main/java/com/aliucord/fragments/SettingsPage.java, Aliucord/src/main/java/com/aliucord/settings/Plugins.java
which fixes lag in plugins page while opening
code is a cursed a bit but idk any better options since if I patch main class what adds this discord pages may get broken too
=> add SettingsPage#removeScrollview, fixes plugin page lag

Aliucord/src/main/java/com/aliucord/Constants.java, Aliucord/src/main/java/com/aliucord/Main.java, Aliucord/src/main/java/com/aliucord/Utils.kt, Aliucord/src/main/java/com/aliucord/fragments/SettingsPage.java, Aliucord/src/main/java/com/aliucord/settings/AliucordPage.kt, Aliucord/src/main/java/com/aliucord/settings/Crashes.kt, Aliucord/src/main/java/com/aliucord/settings/Updater.java, Aliucord/src/main/java/com/aliucord/updater/PluginUpdater.java, Aliucord/src/main/java/com/aliucord/updater/Updater.java, Aliucord/src/main/java/com/aliucord/views/ToolbarButton.java
=> Add 'Aliucord' settings page, Refactor & Cleanup

Aliucord/src/main/java/com/aliucord/coreplugins/SupportWarn.kt
* better check for user confirmation
=> Improve SupportWarn

Aliucord/src/main/java/com/aliucord/Main.java
funny discord with the parser race condition bug
=> fix: user settings parser race condition

Aliucord/src/main/java/com/aliucord/Main.java
Reverts Aliucord/Aliucord#272
Merge this when discord has reverted the change in their api
https://discordstatus.com/incidents/pp6njm8bcwzq
=> Revert "fix: user settings parser race condition"

Aliucord/src/main/java/com/aliucord/coreplugins/CorePlugins.kt, Aliucord/src/main/java/com/aliucord/coreplugins/UploadSize.kt, build.gradle.kts
Increases upload size from 8MB to 25MB
=> feat: 25mb upload size plugin

installer/lib/main.dart, installer/lib/pages/home.dart, installer/lib/utils/themes.dart, installer/pubspec.lock, installer/pubspec.yaml
=> Switch installer to Material 3, add dynamic color

README.md
just in case someone forgot they are modding apps (very rare cases like https://discord.com/channels/811255666990907402/811255667469582420/1051825614077829141)
=> Adding an (obnoxious) reminder that THIS is against TOS

Aliucord/src/main/java/com/aliucord/api/rn/user/RNUserProfile.kt, Aliucord/src/main/java/com/aliucord/api/rn/user/UserProfileData.kt, Aliucord/src/main/java/com/aliucord/coreplugins/CorePlugins.kt, Aliucord/src/main/java/com/aliucord/coreplugins/Pronouns.kt
Displays a user's set pronouns under their username
I made `userProfile` in the `RNUserProfile` class to be nullable because it is null when a user has blocked you (thanks dolfies). That should be backwards compatible, but I'm not sure any other plugins use it in the first place
=> Add Pronouns core plugin

Aliucord/src/main/java/com/aliucord/settings/Plugins.java
I don't think that we should show built-in plugins by default, so I added a toggle for this.
=> feat: add toggle for showing built-in plugins

Aliucord/src/main/java/com/aliucord/Http.java, Aliucord/src/main/java/com/aliucord/api/PatcherAPI.java
Adding @Override annotations aligns with codestyle convention.
=> added missing @override annotations.

Aliucord/src/main/java/com/aliucord/PluginManager.kt, Aliucord/src/main/java/com/aliucord/coreplugins/RestartButton.kt
very useful plugin that should've been core a long time ago
=> feat: merge `RestartButton` plugin into core

Aliucord/src/main/java/com/aliucord/Constants.java, Aliucord/src/main/java/com/aliucord/coreplugins/plugindownloader/PluginDownloader.kt
Depends on #566 being merged first
=> feat(PluginDownloader): allow installing attachment plugin zips

Aliucord/src/main/java/com/aliucord/PluginManager.kt, Aliucord/src/main/java/com/aliucord/coreplugins/RemoveBilling.kt
i made it so billing and links to it is removed including settings, the boosting page and also the gift button
=> feat: remove billing
